# Generated by Django 5.2.17 on 2026-09-09 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('clay', 'Clay'), ('florals', 'Florals'), ('film', 'Film'), ('education', 'Education'), ('cake', 'Cake'), ('research', 'Research'), ('drawings', 'Drawings'), ('textiles', 'Textiles')], help_text='Which leaf on the drawing this section belongs to.', max_length=32, unique=True, verbose_name='Leaf')),
                ('title', models.CharField(help_text='The heading shown when this section is open, e.g. “clay”.', max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='One line under the heading.', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='An opening paragraph. Leave blank and the page skips it entirely, so an unfinished section still looks deliberate.')),
                ('kind', models.CharField(choices=[('gallery', 'Gallery of pictures'), ('research', 'List of publications'), ('teaching', 'Workshops and classes'), ('writing', 'Long-form writing')], default='gallery', help_text='What this section mainly contains.', max_length=20, verbose_name='Layout')),
                ('accent', models.CharField(default='#b5674a', help_text='The colour this leaf turns when hovered, and the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Enter a hex colour such as #b5674a.')], verbose_name='Colour')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first when moving between leaves with the arrow keys.')),
                ('cv', models.FileField(blank=True, help_text='Research sections only. Adds a download button.', upload_to='cv/', verbose_name='CV')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this leaf while you work on it.', verbose_name='Visible on the site')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neida Rodriguez', help_text='Shown in large type at the top of the page.', max_length=120)),
                ('role', models.CharField(blank=True, default='maker · artist · researcher', help_text='The small line under your name.', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='A sentence or two under your name. Leave blank to hide it.')),
                ('about', models.TextField(blank=True, help_text='A longer introduction near the bottom of the page. Leave blank and the whole About section is hidden rather than showing an empty heading.')),
                ('email', models.EmailField(blank=True, help_text='Add an address and it becomes a contact link in the footer.', max_length=254)),
                ('location', models.CharField(blank=True, help_text='For example "Brooklyn, NY". Leave blank to hide it.', max_length=120)),
            ],
            options={
                'verbose_name': 'Your details',
                'verbose_name_plural': 'Your details',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('venue', models.CharField(blank=True, help_text='The journal, conference or institution.', max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Links the title, if you have a link.')),
                ('kind', models.CharField(blank=True, choices=[('article', 'Article'), ('chapter', 'Chapter'), ('talk', 'Talk'), ('poster', 'Poster'), ('thesis', 'Thesis'), ('preprint', 'Preprint')], max_length=20, verbose_name='Type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='portfolio.section')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPEG or PNG.', upload_to='pieces/%Y/%m/')),
                ('title', models.CharField(help_text='Shown when the picture is opened.', max_length=140)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='An optional caption, shown when opened.')),
                ('alt', models.CharField(blank=True, help_text='Describe the picture for people who cannot see it. Worth filling in. Left blank, the title is used instead.', max_length=250, verbose_name='Description for screen readers')),
                ('orientation', models.CharField(choices=[('portrait', 'Taller than wide'), ('landscape', 'Wider than tall'), ('square', 'Square')], default='portrait', help_text='Sets the shape of its cell in the grid.', max_length=12, verbose_name='Shape')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='portfolio.section')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('blurb', models.TextField(blank=True, help_text='A sentence about what it covers.')),
                ('audience', models.CharField(blank=True, help_text='For example "Beginners".', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='portfolio.section')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the link says, e.g. "Instagram".', max_length=60)),
                ('url', models.URLField(help_text='The full address, including https://')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.siteinfo')),
            ],
            options={
                'verbose_name': 'Link',
                'ordering': ('order', 'id'),
            },
        ),
    ]
