# Generated by Django 5.2.17 on 2026-09-09 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cv',
            field=models.FileField(blank=True, help_text='Research sections only. A PDF. Adds a download button.', upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='CV'),
        ),
    ]
