# Generated by Django 5.2.17 on 2026-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_section_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='pieces/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(help_text='A photograph from your phone or camera is exactly right.', upload_to='pieces/%Y/%m/'),
        ),
    ]
